#ifndef GPIO_CONFIG_H
#define  GPIO_CONFIG_H

#define SPI_MLINE_SPI SPI1

#define SPI_MLINE_ENABLE_CLOCK_SPI LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SPI1);

#define SPI_MLINE_ENABLE_GPIO LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA); \
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOB);

#define SPI_MLINE_SCK_PIN LL_GPIO_PIN_3
#define SPI_MLINE_SCK_PORT GPIOB
#define SPI_MLINE_MOSI_PIN LL_GPIO_PIN_7
#define SPI_MLINE_MOSI_PORT GPIOA
#define SPI_MLINE_MISO_PIN LL_GPIO_PIN_4
#define SPI_MLINE_MISO_PORT GPIOB

#define SPI_MLINE_CS_PIN LL_GPIO_PIN_6
#define SPI_MLINE_CS_PORT GPIOE
#define SPI_MLINE_ENABLE_CLOCK_CS LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOE);

#define SPI_MLINE_DMA DMA2
#define SPI_MLINE_DMA_STREAM_TX	LL_DMA_STREAM_3
#define SPI_MLINE_DMA_STREAM_RX	LL_DMA_STREAM_0
#define SPI_MLINE_DMA_CHANNEL LL_DMA_CHANNEL_3

#define SPI_MLINE_DMA_IRQ_RX 56
#define SPI_MLINE_DMA_IRQ_TX 59

#endif
