#ifndef EXLNK_OPTIONS_H_
#define EXLNK_OPTIONS_H_

#define EXLNK_START_DATA_POINT_ADR 4
#define EXLNK_START_DATA_POINT_VAL 13
#define EXLNK_XLXLGR_START_DATA_POINT_VAL 20
#define EXLNK_PCK_ID 17
#define EXLNK_SNS_ID 0x17
#define EXLNK_RAW_ID 0x19


#define EXLNK_DT_MARK_AMPERVOLTS 25
#define EXLNK_DT_MARK_PH 24
#define EXLNK_DT_MARK_TEMPERATURE 23

#endif