#ifndef EXACTO_DATA_STORAGE_REFS_H
#define EXACTO_DATA_STORAGE_REFS_H
#include <errno.h>

#include <framework/mod/options.h>
#include <module/exacto/commander/data_storage_options.h>
#define MODOPS_EXACTOLINK_BUFFER_SZ OPTION_MODULE_GET(exacto__commander__data_storage_options, NUMBER, exactolinkbuffersz)

#define MODOPS_USE_EXTENDED_FUN OPTION_MODULE_GET(exacto__commander__data_storage_options, BOOLEAN, use_extended_fun)
#if MODOPS_USE_EXTENDED_FUN
#define EXDTSTR_EXTENDED
#endif

#define MODOPS_USE_PRINTK OPTION_MODULE_GET(exacto__commander__data_storage_options, BOOLEAN, use_printk)
#if MODOPS_USE_PRINTK
#define PRINTK_ID_FOR_THREAD_ON
#endif


#if MODOPS_EXACTOLINK_BUFFER_SZ == 16
#define EXACTOLINK_MESSAGE_SIZE  16
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 32
#define EXACTOLINK_MESSAGE_SIZE  32 
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 64
#define EXACTOLINK_MESSAGE_SIZE  64
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 128
#define EXACTOLINK_MESSAGE_SIZE  128 
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 256
#define EXACTOLINK_MESSAGE_SIZE  256
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 512
#define EXACTOLINK_MESSAGE_SIZE  512
#elif MODOPS_EXACTOLINK_BUFFER_SZ == 1024
#define EXACTOLINK_MESSAGE_SIZE  1024
#else
#error Unsupported exactolink buffer sz
#endif



#define EXDTSTR_SINGLE_DATA_STR_LENGTH 6

#define EXACTOLINK_SD_FRAME_SIZE 512
#define EXACTOLINK_SD_PT_ID 0
#define EXACTOLINK_SD_PT_TYPE 1
#define EXACTOLINK_SD_PT_COUNTER 2
#define EXACTOLINK_SD_PT_LEN 6
#define EXACTOLINK_SD_PT_DATA_START 8

#define THREAD_CONTROL_BUFFER_SZ 16
#define THREAD_OUTPUT_TYPES_SZ 2
#define SERVICES_COUNT 5

#define EXACTOLINK_START_DATA_POINT_ADR 4
#define EXACTOLINK_START_DATA_POINT_VAL 13
#define EXACTOLINK_XLXLGR_START_DATA_POINT_VAL 20
#define EXACTOLINK_PCK_ID 17
#define EXACTOLINK_SNS_ID 0x17
#define EXACTOLINK_RAW_ID 0x19

#define EXACTOLINK_LSM303AH_TYPE0_ONE_INFOPACK_LENGTH 19
#define EXACTOLINK_APOLLON_SPI_PACK_SIZE EXACTOLINK_LSM303AH_TYPE0_ONE_INFOPACK_LENGTH*25

#endif //EXACTO_DATA_STORAGE_H
